# Generated by Django 4.2.7 on 2026-01-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('date_key', models.CharField(db_column='dateKey', max_length=50, primary_key=True, serialize=False)),
                ('focus_subject', models.CharField(db_column='focusSubject', max_length=255)),
                ('total_available_in_subject', models.IntegerField(db_column='totalAvailableInSubject', default=0)),
                ('max_planned_questions', models.IntegerField(db_column='maxPlannedQuestions', default=35)),
                ('question_ids', models.JSONField(db_column='questionIds', default=list)),
                ('answered_count', models.IntegerField(db_column='answeredCount', default=0)),
                ('correct_count', models.IntegerField(db_column='correctCount', default=0)),
                ('wrong_count', models.IntegerField(db_column='wrongCount', default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('is_complete', models.BooleanField(db_column='isComplete', default=False)),
                ('motivational_quote', models.TextField(blank=True, db_column='motivationalQuote', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('last_updated', models.DateTimeField(auto_now=True, db_column='lastUpdated')),
            ],
            options={
                'db_table': 'dailyPlans',
                'ordering': ['-date_key'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(db_column='examId', max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('question_ids', models.JSONField(db_column='questionIds', default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(db_column='questionId', max_length=255, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('choices', models.JSONField(default=list)),
                ('correct_answer', models.CharField(db_column='correctAnswer', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['subject', 'topic'],
            },
        ),
        migrations.CreateModel(
            name='ThemePreferences',
            fields=[
                ('id', models.CharField(default='themePreferences', max_length=50, primary_key=True, serialize=False)),
                ('favorite_light_theme', models.CharField(db_column='favoriteLightTheme', default='light', max_length=50)),
                ('favorite_dark_theme', models.CharField(db_column='favoriteDarkTheme', default='dark', max_length=50)),
                ('auto_mode', models.BooleanField(db_column='autoMode', default=False)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('session_id', models.CharField(db_column='sessionId', max_length=255, primary_key=True, serialize=False)),
                ('exam_id', models.CharField(blank=True, db_column='examId', max_length=255, null=True)),
                ('mode', models.CharField(max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('current_index', models.IntegerField(db_column='currentIndex', default=0)),
                ('question_ids', models.JSONField(db_column='questionIds', default=list)),
                ('answers', models.JSONField(default=dict)),
                ('time_spent', models.JSONField(db_column='timeSpent', default=dict)),
                ('is_complete', models.BooleanField(db_column='isComplete', default=False)),
                ('is_paused', models.BooleanField(db_column='isPaused', default=False)),
                ('time_per_question', models.IntegerField(blank=True, db_column='timePerQuestion', null=True)),
                ('plan_date_key', models.CharField(blank=True, db_column='planDateKey', max_length=50, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_column='startedAt')),
                ('last_updated', models.DateTimeField(auto_now=True, db_column='lastUpdated')),
            ],
            options={
                'db_table': 'examSessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['is_complete'], name='examSession_isCompl_ba7f05_idx'), models.Index(fields=['plan_date_key'], name='examSession_planDat_e2aab4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('attempt_id', models.CharField(db_column='attemptId', max_length=255, primary_key=True, serialize=False)),
                ('question_id', models.CharField(db_column='questionId', max_length=255)),
                ('selected_answer', models.CharField(db_column='selectedAnswer', max_length=255)),
                ('is_correct', models.BooleanField(db_column='isCorrect')),
                ('time_spent', models.IntegerField(db_column='timeSpent', default=0)),
                ('subject', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_id', models.CharField(blank=True, db_column='examId', max_length=255, null=True)),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_date_key', models.CharField(blank=True, db_column='planDateKey', max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['question_id'], name='attempts_questio_7c1e96_idx'), models.Index(fields=['subject'], name='attempts_subject_184ebd_idx'), models.Index(fields=['subject', 'topic'], name='attempts_subject_25ad99_idx'), models.Index(fields=['plan_date_key'], name='attempts_planDat_487a05_idx')],
            },
        ),
    ]
