# Generated by Django 4.2.7 on 2026-01-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(db_index=True, max_length=255)),
                ('document_id', models.CharField(db_index=True, max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'firebase_collections',
                'indexes': [models.Index(fields=['collection_name'], name='firebase_co_collect_54748d_idx')],
                'unique_together': {('collection_name', 'document_id')},
            },
        ),
    ]
