# Generated by Django 4.2.7 on 2026-10-03 21:22

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_per_user_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, upload_to=api.models.exam_import_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('page_count', models.IntegerField(default=0)),
                ('pages_processed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('ready', 'Ready for review'), ('failed', 'Failed'), ('published', 'Published')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('draft_questions', models.JSONField(default=list)),
                ('exam_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'examImports',
                'ordering': ['-created_at'],
            },
        ),
    ]
