# Generated by Django 4.2.7 on 2026-10-03 21:49

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_exam_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_key', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('topics', models.JSONField(default=list)),
                ('plan_date_key', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('thinking', 'Thinking'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'studySessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.studysession')),
            ],
            options={
                'db_table': 'studyMessages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudyDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=api.models.study_doc_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('topics', models.JSONField(default=list)),
                ('key_points', models.JSONField(default=list)),
                ('text_excerpt', models.TextField(blank=True)),
                ('page_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('describing', 'Describing'), ('ready', 'Ready'), ('failed', 'Failed')], default='describing', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'studyDocs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(fields=('owner', 'context_key'), name='unique_study_session_per_context'),
        ),
    ]
