# Generated by Django 4.2.7 on 2026-10-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_study_docs_and_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='session_id',
            field=models.CharField(blank=True, db_column='sessionId', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('session_id__isnull', False)), fields=('owner', 'session_id', 'question_id'), name='unique_attempt_per_session_question'),
        ),
    ]
