# Generated by Django 4.2.7 on 2026-10-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_attempt_session_dedupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='cursor_agent_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
