# Generated by Django 4.2.7 on 2026-10-04 23:15

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_study_session_cursor_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, upload_to=api.models.blueprint_import_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('page_count', models.IntegerField(default=0)),
                ('pages_processed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('ready', 'Ready for review'), ('failed', 'Failed'), ('applied', 'Applied')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('draft', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blueprintImports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to=settings.AUTH_USER_MODEL)),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_blueprints', to='api.blueprintimport')),
            ],
            options={
                'db_table': 'userBlueprints',
                'ordering': ['-applied_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BlueprintCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('theme_name', models.CharField(blank=True, max_length=255)),
                ('theme_order', models.IntegerField(default=0)),
                ('theme_credit_hours', models.FloatField(blank=True, null=True)),
                ('theme_item_share', models.FloatField(blank=True, null=True)),
                ('credit_hours', models.FloatField(blank=True, null=True)),
                ('item_count', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('focus_notes', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.userblueprint')),
            ],
            options={
                'db_table': 'blueprintCourses',
                'ordering': ['theme_order', 'sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='userblueprint',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner',), name='one_active_blueprint_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='blueprintcourse',
            constraint=models.UniqueConstraint(fields=('blueprint', 'name'), name='unique_course_per_blueprint'),
        ),
    ]
